---
galaxy_info:
  author: AnyiTech DevOps Team
  description: Install system dependencies for DevOps Stage 6
  company: HNG
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
